# Generated by Django 4.1.3 on 2022-11-07 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sold_cars',
            name='picture',
            field=models.ImageField(blank=True, upload_to='car_images/'),
        ),
    ]
